/**@file filter_coefficients.h
 *	
 * @author Jenil Jain
 * @copyright Copyright 2015 Insensi Inc. All rights reserved.
 * This project is released under the GNU Public License.
 *
 * @brief File containing coefficients for various filters used by the program.
 *
 * All Coefficients are generated by program 
 * <a href="http://www-users.cs.york.ac.uk/~fisher/mkfilter/trad.html">mkfilter</a>.				
 * Corner frequencies can be calculated from 
 * <a href="http://www.sengpielaudio.com/calculator-cutoffFrequencies.htm">cut-off</a>. <BR>
 * 	
 * You can design your filter for a particular frequency just by changing the
 * parameters. All the filters used are IIR and the general equation for it, is
 *
 * y[n] = c0*x[n] + c1*x[n-1] + ... + cM*x[n-M] - ( d1*y[n-1] + d2*y[n-2] + ... + dN*y[n-N])
 * where N = no. of previous outputs &                  <BR>
 *      M = no. of previous inputs                      <BR>
 *      c1,c2,...,cM = input coefficients               <BR>
 *      d1,d2,...,dN = output coefficients              <BR>
 *      x[n] = input values                             <BR>
 *      y[n] = output values                            <BR>
 *
 * Example code for a 3rd order BandPass filter 
 * @code #define NZEROS 6
        #define NPOLES 6
        #define GAIN   6.035463052e+03

        static float xv[NZEROS+1], yv[NPOLES+1];
        static d_coef[NZEROS + 1] = {-0.7960564529, 4.8728234960, -12.5192737550, 
						        17.2778325650, -13.5086884650, 5.6733267812, 1.0}

        static c_coef[NZEROS + 1] = {-1, 0, 3, 0, -3, 0, 1}

        static int filterloop(int input)
        {
            xv[0] = xv[1]; xv[1] = xv[2]; xv[2] = xv[3]; 
            xv[3] = xv[4]; xv[4] = xv[5]; xv[5] = xv[6]; 
        yv[0] = yv[1]; yv[1] = yv[2]; yv[2] = yv[3]; 
        yv[3] = yv[4]; yv[4] = yv[5]; yv[5] = yv[6]; 

        xv[6] = input / GAIN;

        yv[6] = (c_coef[0] * xv[0]) + (c_coef[1] * xv[1]) + 
            (c_coef[2] * xv[2]) + (c_coef[3] * xv[3]) + 
            (c_coef[4] * xv[4]) + (c_coef[5] * xv[5]) +

            (d_coef[0] * yv[0]) + (d_coef[1] * yv[1]) + 
            (d_coef[2] * yv[2]) + (d_coef[3] * yv[3]) + 
            (d_coef[4] * yv[4]) + (d_coef[5] * yv[5]);
        return (int) yv[6];
        }
   @endcode	
 */

#ifndef FILTER_COEFFICIENTS_H
#define FILTER_COEFFICIENTS_H

#define BW              800	///< Bandwidth
#define NZEROS_POLES    6	/**< No. of zeros depends on order of the filter
                                For a 3rd order Bandpass filter, zeros and poles
                                are 6. But for a 3rd order Low-Pass or High-Pass
                                filter it is 3. So to keep the number of poles &
                                zeros constant we are using 3rd order Bandpass
                                and 6th order Low-pass for demodulation */

/// C coefficient for 3rd order Bandpass Filter
static const int c_coef_3rd_bp [NZEROS_POLES + 1] = {-1, 0, 3, 0, -3, 0, 1};

/// C coefficient for 6th order Lowpass Filter	
static const int c_coef_6th_lp [NZEROS_POLES + 1] = {1, 6, 15, 20, 15, 6, 1};	

/// Zeros for initializing xv and yv array
static const int zeros [NZEROS_POLES + 1] = {0, 0, 0, 0, 0, 0, 0};	



/************************************************************************************************/
/**************************************** 44100 Hz **********************************************/
/************************************************************************************************/


/*********************************  MARK BANDPASS  ********************************/

/**@brief Coefficients for Mark filters for 1200Hz and 44.1 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 44100
 * @param corner1 864.911
 * @param corner2 1664.911
 */
static const double gain_1200hz	                        = 6.035447139e+03 ;
static const double d_coef_1200hz [NZEROS_POLES + 1]    = {-0.7960564529,
4.8853503505, -12.5704962310, 17.3572300720, -13.5639614690, 5.6879115366, 1.0} ;


/**@brief Coefficients for Mark filters for 1300Hz and 44.1 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 44100
 * @param corner1 960.147
 * @param corner2 1760.147
 */
static const double gain_1300hz	                        = 6.035463052e+03 ;
static const double d_coef_1300hz [NZEROS_POLES + 1]    = {-0.7960564529, 
4.8728234960, -12.5192737550, 17.2778325650, -13.5086884650, 5.6733267812, 1.0} ;


/*********************************  SPACE BANDPASS  *******************************/

/**@brief Coefficients for Space filters for 2100Hz and 44.1 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 44100
 * @param corner1 1737.756
 * @param corner2 2537.756
 */
static const double gain_2100hz	                        = 6.035489699e+03 ;
static const double d_coef_2100hz [NZEROS_POLES + 1]    = {-0.7960564529, 
4.7372163175, -11.9731917700, 16.4353856510, -12.9194238570, 5.5154421711, 1.0} ;


/**@brief Coefficients for Space filters for 2200Hz and 44.1 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 44100
 * @param corner1 1737.756
 * @param corner2 2537.756
 */
static const double gain_2200hz	                        = 6.035490118e+03 ;
static const double d_coef_2200hz [NZEROS_POLES + 1]    = {-0.7960564529, 
4.7158930488, -11.8887264470, 16.3057248700, -12.8282792550, 5.4906159340, 1.0} ;


/**********************************  LOW PASS  ************************************/

/**@brief Coefficients for Low Pass filter for 1700Hz and 44.1 Khz sampling 
 *
 * Since 1700 is center of both ranges 1200-2200 and 1300-2100 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Low Pass
 * @param order 6
 * @param sample_rate 44100
 * @param corner1 1700
 */
static const double gain_lp_1700hz                      = 4.921530591e+05 ;
static const double d_coef_lp_1700hz [NZEROS_POLES + 1] = {-0.3911214670, 
2.7125767203, -7.8710687721, 12.2354456210, -10.7505803000, 5.0646181573, 1.0} ;



/************************************************************************************************/
/**************************************** 48000 Hz **********************************************/
/************************************************************************************************/


/*********************************  MARK BANDPASS  ********************************/

/**@brief Coefficients for Mark filters for 1200Hz and 48 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 48000
 * @param corner1 864.911
 * @param corner2 1664.911
 */
static const double gain_1200hz_48                      = 7.714531525e+03 ;
static const double d_coef_1200hz_48 [NZEROS_POLES + 1] = {-0.8109608719,
4.9734833008, -12.7760535460, 17.5948994070, -13.7006793120, 5.7192975419, 1.0} ;


/**@brief Coefficients for Mark filters for 1300Hz and 48 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 48000
 * @param corner1 960.147
 * @param corner2 1760.147
 */
static const double gain_1300hz_48                      = 7.714552008e+03 ;
static const double d_coef_1300hz_48 [NZEROS_POLES + 1] = {-0.8109608719, 
4.9627363056, -12.7321344850, 17.5269785470, -13.6535802120, 5.7069389474, 1.0} ;


/*********************************  SPACE BANDPASS  *******************************/

/**@brief Coefficients for Space filters for 2100Hz and 48 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 48000
 * @param corner1 1737.756
 * @param corner2 2537.756
 */
static const double gain_2100hz_48                      = 7.714586427e+03 ;
static const double d_coef_2100hz_48 [NZEROS_POLES + 1] = {-0.8109608719, 
4.8463050158, -12.2624122920, 16.8034849110, -13.1498469240, 5.5730478395, 1.0} ;


/**@brief Coefficients for Space filters for 2200Hz and 48 Khz sampling 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 48000
 * @param corner1 1737.756
 * @param corner2 2537.756
 */
static const double gain_2200hz_48                      = 7.714586976e+03 ;
static const double d_coef_2200hz_48 [NZEROS_POLES + 1] = {-0.8109608719, 
4.8279816404, -12.1895052890, 16.6916642700, -13.0716609570, 5.5519767250, 1.0} ;


/**********************************  LOW PASS  ************************************/


/**@brief Coefficients for Low Pass filter for 1700Hz and 48 Khz sampling 
 *
 * Since 1700 is center of both ranges 1200-2200 and 1300-2100 
 *
 * Filter Design parameters	
 * @param filtertype Butterworth
 * @param passtype Low Pass
 * @param order 6
 * @param sample_rate 48000
 * @param corner1 1700
 */
static const double gain_lp_1700hz_48                   = 7.911546151e+05 ;
static const double d_coef_lp_1700hz_48 [NZEROS_POLES + 1] = {-0.4222972557, 
2.8967245878, -8.3083998149, 12.7576882370, -11.0643521500, 5.1405555009, 1.0} ;


/************************************************************************************************/
/**************************************** 24000 Hz **********************************************/
/************************************************************************************************/


/*********************************  MARK BANDPASS  ********************************/

/**@brief Coefficients for Mark filters for 1200Hz and 24 Khz sampling 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 24000
 * @param corner1 864.911
 * @param corner2 1664.911
 */
static const double gain_1200hz_24                      = 1.062338387e+03 ;
static const double d_coef_1200hz_24 [NZEROS_POLES + 1] = {
 -0.6572747021,
  4.0112663417,
-10.4266852309,
 14.7588556648,
-11.9945952080,
  5.3076643313,
    1.0} ;


/**@brief Coefficients for Mark filters for 1300Hz and 24 Khz sampling 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 24000
 * @param corner1 960.147
 * @param corner2 1760.147
 */
static const double gain_1300hz_24                      = 1.062340894e+03 ;
static const double d_coef_1300hz_24 [NZEROS_POLES + 1] = {
 -0.6572747021,
  3.9756377692,
-10.2820186612,
 14.5300247961,
-11.8281276268,
  5.2605209888,
    1.0} ;


/*********************************  SPACE BANDPASS  *******************************/

/**@brief Coefficients for Space filters for 2100Hz and 24 Khz sampling Q fsctor 2.625
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 24000
 * @param corner1 1737.756 
 * @param corner2 2537.756
 */
static const double gain_2100hz_24                      = 1.062344869e+03 ;
static const double d_coef_2100hz_24 [NZEROS_POLES + 1] = {
 -0.6572747021,
  3.5945838274,
 -8.8155042240,
 12.2415102377,
-10.1406119042,
  4.7563145254,
    1.0} ;


/**@brief Coefficients for Space filters for 2200Hz and 24 Khz sampling 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 24000
 * @param corner1 1820.506
 * @param corner2 2658.601
 */static const double gain_2200hz_24                      = 9.322781121e+02;
static const double d_coef_2200hz_24 [NZEROS_POLES + 1] = {
-0.6442189191,
 3.4756874203,
-8.4822356328,
11.7852181371,
-9.8228466728,
 4.6611083979,
    1.0} ;


/**********************************  LOW PASS  ************************************/


/**@brief Coefficients for Low Pass filter for 1700Hz and 48 Khz sampling 
 *
 * Since 1700 is center of both ranges 1200-2200 and 1300-2100 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Low Pass
 * @param order 6
 * @param sample_rate 24000
 * @param corner1 1700
 */
static const double gain_lp_1700hz_24                   =  1.776345832e+04  ;
static const double d_coef_lp_1700hz_24 [NZEROS_POLES + 1] = {
-0.1758985916,
 1.3573977011,
-4.4184975072,
 7.7786196065,
-7.8282903649,
 4.2830662540,
    1.0} ;

/************************************************************************************************/
/**************************************** 16000 Hz **********************************************/
/************************************************************************************************/

/* FSK decode fail ... */

/*********************************  MARK BANDPASS  ********************************/

static const double gain_1200hz_16                      = 3.450407729e+02 ;
static const double d_coef_1200hz_16 [NZEROS_POLES + 1] = {-0.5320753683,
	3.1381363581, -8.1321890445, 11.7763561920, -10.0414792500, 4.7835061525, 1.0} ;


static const double gain_1300hz_16                      = 7.714552008e+03 ;
static const double d_coef_1300hz_16 [NZEROS_POLES + 1] = {-0.8109608719, 
	4.9627363056, -12.7321344850, 17.5269785470, -13.6535802120, 5.7069389474, 1.0} ;


static const double gain_2100hz_16                      = 7.714586427e+03 ;
static const double d_coef_2100hz_16 [NZEROS_POLES + 1] = {-0.8109608719, 
	4.8463050158, -12.2624122920, 16.8034849110, -13.1498469240, 5.5730478395, 1.0} ;

/*
static const double gain_2200hz_16                      = 3.450423755e+02 ;
static const double d_coef_2200hz_16 [NZEROS_POLES + 1] = {-0.5320753683, 
	2.2795472690, -5.2023382825, 7.1423622606, -6.4198613572, 3.4747465189, 1.0} ;
*/
static const double gain_2200hz_16                      = 3.039407281e+02 ;
static const double d_coef_2200hz_16 [NZEROS_POLES + 1] = {
-0.5161823940,
 2.2203755300,
-5.0895081414,
 7.0212063475,
-6.3443555818,
 3.4541106423,
  1.0} ;

/**********************************  LOW PASS  ************************************/


static const double gain_lp_1700hz_16                   = 2.155293674e+03  ;
static const double d_coef_lp_1700hz_16 [NZEROS_POLES + 1] = {-0.0712022265, 
	0.6102683340, -2.2329558363, 4.4846591081, -5.2494746975, 3.4290109889, 1.0} ;


/************************************************************************************************/
/**************************************** 12000 Hz **********************************************/
/************************************************************************************************/


/*********************************  MARK BANDPASS  ********************************/

/**@brief Coefficients for Mark filters for 1200Hz and 12 Khz sampling 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 12000
 * @param corner1 864.911
 * @param corner2 1664.911
 */
static const double gain_1200hz_12                      = 1.588060129e+02 ;
static const double d_coef_1200hz_12 [NZEROS_POLES + 1] = {
-0.4299088249,
 2.3683813621,
-6.0374054470,
 8.9010609313,
-8.0064981087,
 4.1661842552,
    1.0} ;


/**@brief Coefficients for Mark filters for 1300Hz and 12 Khz sampling 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 12000
 * @param corner1 960.147
 * @param corner2 1760.147
 */
static const double gain_1300hz_12                      = 1.588062303e+02 ;
static const double d_coef_1300hz_12 [NZEROS_POLES + 1] = {
-0.4299088248,
 2.2733801259,
-5.6923301282,
 8.3366012926,
-7.5474791074,
 3.9990690007,
    1.0} ;


/*********************************  SPACE BANDPASS  *******************************/

/**@brief Coefficients for Space filters for 2100Hz and 12 Khz sampling Q fsctor 2.625
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 12000
 * @param corner1 1737.756 
 * @param corner2 2537.756
 */
static const double gain_2100hz_12                      = 1.588064875e+02 ;
static const double d_coef_2100hz_12 [NZEROS_POLES + 1] = {
-0.4299088248,
 1.3103332769,
-2.9915918119,
 3.8693867290,
-3.9549584675,
 2.3049876827,
    1.0} ;


/**@brief Coefficients for Space filters for 2200Hz and 12 Khz sampling 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 12000
 * @param corner1 1820.506
 * @param corner2 2658.601
 */static const double gain_2200hz_12                      = 1.403567646e+02;
static const double d_coef_2200hz_12 [NZEROS_POLES + 1] = {
-0.4126832831,
 1.1267441664,
-2.6340218792,
 3.2832400848,
-3.5260877253,
 2.0373598521,
    1.0} ;


/**********************************  LOW PASS  ************************************/


/**@brief Coefficients for Low Pass filter for 1700Hz and 12 Khz sampling 
 *
 * Since 1700 is center of both ranges 1200-2200 and 1300-2100 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Low Pass
 * @param order 6
 * @param sample_rate 12000
 * @param corner1 1700
 */
static const double gain_lp_1700hz_12                   =  5.117871377e+02  ;
static const double d_coef_lp_1700hz_12 [NZEROS_POLES + 1] = {
-0.0275377378,
 0.2593387339,
-1.0581216735,
 2.4089098631,
-3.2867379599,
 2.5790967842,
    1.0} ;


/************************************************************************************************/
/**************************************** 8000 Hz **********************************************/
/************************************************************************************************/

/* FSK decode fail ... */

/*********************************  MARK BANDPASS  ********************************/

/**@brief Coefficients for Mark filters for 1200Hz and 8 Khz sampling 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 8000
 * @param corner1 864.911
 * @param corner2 1664.911
 */
static const double gain_1200hz_8                      = 5.525184257e+01 ;
static const double d_coef_1200hz_8 [NZEROS_POLES + 1] = {
-0.2780599176,
 1.1575634693,
-2.8164295167,
 4.1755819526,
-4.2969514653,
 2.7317060672,
    1.0} ;


/**@brief Coefficients for Mark filters for 1300Hz and 8 Khz sampling 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 8000
 * @param corner1 960.147
 * @param corner2 1760.147
 */
static const double gain_1300hz_8                      = 5.525186386e+01 ;
static const double d_coef_1300hz_8 [NZEROS_POLES + 1] = {
-0.2780599176,
 1.0215252617,
-2.4550404844,
 3.5291102371,
-3.7357081520,
 2.4106727875,
    1.0} ;


/*********************************  SPACE BANDPASS  *******************************/

/**@brief Coefficients for Space filters for 2100Hz and 8 Khz sampling Q fsctor 2.625
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 8000
 * @param corner1 1737.756 
 * @param corner2 2537.756
 */
static const double gain_2100hz_8                      = 5.525187587e+01 ;
static const double d_coef_2100hz_8 [NZEROS_POLES + 1] = {
-0.2780599176,
-0.2290171862,
-1.2468336550,
-0.6744560554,
-1.8593423981,
-0.5404521253,
    1.0} ;


/**@brief Coefficients for Space filters for 2200Hz and 8 Khz sampling 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Bandpass
 * @param order 3
 * @param sample_rate 8000
 * @param corner1 1820.506
 * @param corner2 2658.601
 */static const double gain_2200hz_8                      = 4.910096594e+01;
static const double d_coef_2200hz_8 [NZEROS_POLES + 1] = {
-0.2608995292,
-0.3772883661,
-1.3112860058,
-1.1496962414,
-1.9965797700,
-0.9294040584,
    1.0} ;


/**********************************  LOW PASS  ************************************/


/**@brief Coefficients for Low Pass filter for 1700Hz and 8 Khz sampling 
 *
 * Since 1700 is center of both ranges 1200-2200 and 1300-2100 
 *
 * Filter Design parameters 
 * @param filtertype Butterworth
 * @param passtype Low Pass
 * @param order 6
 * @param sample_rate 12000
 * @param corner1 1700
 */
static const double gain_lp_1700hz_8                   =  7.275156035e+01  ;
static const double d_coef_lp_1700hz_8 [NZEROS_POLES + 1] = {
-0.0034681988,
 0.0339956940,
-0.1949053270,
 0.4681867822,
-1.0739546444,
 0.8904394762,
    1.0} ;
#endif
